feat: allow role and group for entities in training data
botfront/botfront pull request #739
Opened 2020-09-02 16:04 UTC by pheel

- [ ] I wrote tests for the feature
- [ ] I documented the feature if needed

If the feature is a refactor, please explain why your way is better

2020-09-02 20:42 UTC, znat commented
<img width="446" alt="Capture d’écran 2020-09-02 à 16 17 53" src="https://user-images.githubusercontent.com/3694634/92033788-3e759200-ed3a-11ea-8687-bcfbf954bb45.png">

Can the labels have the same widths, input be fluids?

_Group_, _Synonym value_ and _Role_ should be capitalized

Also, _Synonym value_ should be on a single line.

<img width="342" alt="Capture d’écran 2020-09-02 à 16 37 51" src="https://user-images.githubusercontent.com/3694634/92034052-ad52eb00-ed3a-11ea-8050-3f7839f0a283.png">

Instead of buttons, we can have plain links (left aligned)
+ Synonym + Group [+ Role](url)

2020-09-02 21:09 UTC, pheel commented
> <img alt="Capture d’écran 2020-09-02 à 16 17 53" width="446" src="https://user-images.githubusercontent.com/3694634/92033788-3e759200-ed3a-11ea-8687-bcfbf954bb45.png">
> 
> Can the labels have the same widths, input be fluids?
> 
👍 
> _Group_, _Synonym value_ and _Role_ should be capitalized
> 
👍 
> Also, _Synonym value_ should be on a single line.
> 
> <img alt="Capture d’écran 2020-09-ttt x02 à 16 37 51" width="342" src="https://user-images.githubusercontent.com/3694634/92034052-ad52eb00-ed3a-11ea-8050-3f7839f0a283.png">
> 
> If _Synonym value_ is too long then stick to _Value_
Stuck to _Value_

2020-09-02 21:13 UTC, kenrilea requested changes

2020-09-03 14:35 UTC, kenrilea requested changes
the delete icons in the stories screen have a minor style bug.

<img width="462" alt="Screen Shot 2020-09-03 at 10 33 28 AM" src="https://user-images.githubusercontent.com/49006070/92129180-30bf1b80-edd1-11ea-97aa-4927825ec6a6.png">

2020-09-03 21:43 UTC, kenrilea approved these changes

2020-09-04 16:18 UTC, merged